<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnidadOrganizacionalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('unidad_organizacionals')->insert([
            [
                'descripcion' => 'PRESIDENCIA EJECUTIVA',
                'sigla' => 'PRE',
                'nivel' => '3',
                'dependencia'=> '0',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,

            ],
            [
                'descripcion' => 'SECRETARIA GENERAL',
                'sigla' => 'SGE',
                'nivel' => '2',
                'dependencia'=> '1',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'AREA DE SISTEMAS OF CENTRAL',
                'sigla' => 'SGE/SIS',
                'nivel' => '3',
                'dependencia'=> '2',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'AREA DE GESTION DOCUMENTAL',
                'sigla' => 'SGE/DOC',
                'nivel' => '3',
                'dependencia'=> '2',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'AREA DE COMUNICACIONES',
                'sigla' => 'SGE/COM',
                'nivel' => '3',
                'dependencia'=> '2',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'COORD. CON MOVIMIENTOS SOCIALES',
                'sigla' => 'SGE/CMS',
                'nivel' => '3',
                'dependencia'=> '2',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'AREA DE COORDINACION INTERINSTITUCIONAL',
                'sigla' => 'SGE/COO',
                'nivel' => '3',
                'dependencia'=> '2',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'UNIDAD DE AUDITORIA',
                'sigla' => 'UAI',
                'nivel' => '3',
                'dependencia'=> '1',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'UNIDAD DE TRANSPARENCIA Y LUCHA CONTRA LA CORRUPCION',
                'sigla' => 'UTR',
                'nivel' => '3',
                'dependencia'=> '1',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'GERENCIA GENERAL',
                'sigla' => 'GEG',
                'nivel' => '3',
                'dependencia'=> '1',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'UNIDAD DE PLANIFICACION Y GESTION DE CALIDAD',
                'sigla' => 'GEG/UPC',
                'nivel' => '3',
                'dependencia'=> '8',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'COORD. GRAL. FINANCIAMIENTO EXTERNO',
                'sigla' => 'GEC/CFE',
                'nivel' => '3',
                'dependencia'=> '9',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'GERENCIA NACIONAL ADMINISTRATIVA FINANCIERA',
                'sigla' => 'GNA',
                'nivel' => '3',
                'dependencia'=> '1',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'SUBGERENCIA DE ASUNTOS ADMINISTRATIVOS',
                'sigla' => 'GNA/SAA',
                'nivel' => '3',
                'dependencia'=> '10',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'AREA DE CONTRATACIONES',
                'sigla' => 'GNA/SAA/ACC',
                'nivel' => '3',
                'dependencia'=> '11',
                'dependencia1'=> '10',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'UNIDAD DE RECURSOS HUMANOS',
                'sigla' => 'GNA/SAA/ARH',
                'nivel' => '3',
                'dependencia'=> '11',
                'dependencia1'=> '10',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'AREA DE BIENES Y SERVICIOS',
                'sigla' => 'GNA/SAA/ASG',
                'nivel' => '3',
                'dependencia'=> '11',
                'dependencia1'=> '10',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'TRANSPORTES OF CENTRAL',
                'sigla' => 'GNA/SAA/TRA',
                'nivel' => '3',
                'dependencia'=> '11',
                'dependencia1'=> '10',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'SUBGERENCIA DE ASUNTOS FINANCIEROS',
                'sigla' => 'GNA/SAF',
                'nivel' => '2',
                'dependencia'=> '10',
                'dependencia1'=> '10',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'AREA DE TESORERIA',
                'sigla' => 'GNA/SAF/ATE',
                'nivel' => '3',
                'dependencia'=> '15',
                'dependencia1'=> '10',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'AREA CONTABILIDAD',
                'sigla' => 'GNA/SAF/ACO',
                'nivel' => '3',
                'dependencia'=> '15',
                'dependencia1'=> '10',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'AREA DE PRESUPUESTO',
                'sigla' => 'GNA/SAF/APT',
                'nivel' => '3',
                'dependencia'=> '15',
                'dependencia1'=> '10',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'AREA CIERRE DE PROYECTOS',
                'sigla' => 'ACP',
                'nivel' => '3',
                'dependencia'=> '11',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'GERENCIA NACIONAL TECNICA',
                'sigla' => 'GNT',
                'nivel' => '2',
                'dependencia'=> '1',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'GERENCIA DE PROYECTOS',
                'sigla' => 'GP',
                'nivel' => '3',
                'dependencia'=> '19',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'SUBGERENCIA DE CONSTRUCCION',
                'sigla' => 'GNT/SCT',
                'nivel' => '3',
                'dependencia'=> '19',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'SUBGERENCIA DE CONSERVACION VIAL',
                'sigla' => 'GNT/SCV',
                'nivel' => '3',
                'dependencia'=> '19',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'SUBGERENCIA SOCIOAMBIENTAL',
                'sigla' => 'GNT/SSA',
                'nivel' => '3',
                'dependencia'=> '19',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'LABORATORIO',
                'sigla' => 'GNT/SCT/LAB',
                'nivel' => '3',
                'dependencia'=> '77',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'GERENCIA NACIONAL JURIDICA',
                'sigla' => 'GNJ',
                'nivel' => '3',
                'dependencia'=> '0',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'SUBGERENCIA DE ASUNTOS JURIDICOS',
                'sigla' => 'GNJ/SAJ',
                'nivel' => '2',
                'dependencia'=> '24',
                'dependencia1'=> '0',
                'fkp_departamento'=>11,
            ],
            [
                'descripcion' => 'GERENCIA REGIONAL LA PAZ',
                'sigla' => 'GLP',
                'nivel' => '3',
                'dependencia'=> '0',
                'dependencia1'=> '0',
                'fkp_departamento'=>2,
            ],
            [
                'descripcion' => 'AREA TECNICA',
                'sigla' => 'GLP/RTE',
                'nivel' => '2',
                'dependencia'=> '26',
                'dependencia1'=> '0',
                'fkp_departamento'=>2,
            ],
            [
                'descripcion' => 'AREA ADMINISTRATIVA',
                'sigla' => 'GLP/RAD',
                'nivel' => '2',
                'dependencia'=> '26',
                'dependencia1'=> '0',
                'fkp_departamento'=>2,
            ],
            [
                'descripcion' => 'AREA JURIDICA',
                'sigla' => 'GLP/RJU',
                'nivel' => '2',
                'dependencia'=> '26',
                'dependencia1'=> '0',
                'fkp_departamento'=>2,
            ],
            [
                'descripcion' => 'AREA DE SISTEMAS',
                'sigla' => 'GLP/SIS',
                'nivel' => '2',
                'dependencia'=> '26',
                'dependencia1'=> '0',
                'fkp_departamento'=>2,
            ],
            [
                'descripcion' => 'GERENCIA REGIONAL SANTA CRUZ',
                'sigla' => 'GSC',
                'nivel' => '3',
                'dependencia'=> '0',
                'dependencia1'=> '0',
                'fkp_departamento'=>4,
            ],
            [
                'descripcion' => 'AREA TECNICA',
                'sigla' => 'GSC/RTE',
                'nivel' => '2',
                'dependencia'=> '31',
                'dependencia1'=> '0',
                'fkp_departamento'=>4,
            ],
            [
                'descripcion' => 'AREA ADMINISTRATIVA',
                'sigla' => 'GSC/RAD',
                'nivel' => '2',
                'dependencia'=> '31',
                'dependencia1'=> '0',
                'fkp_departamento'=>4,
            ],
            [
                'descripcion' => 'AREA JURIDICA',
                'sigla' => 'GSC/RJU',
                'nivel' => '2',
                'dependencia'=> '31',
                'dependencia1'=> '0',
                'fkp_departamento'=>4,
            ],
            [
                'descripcion' => 'AREA DE SISTEMAS',
                'sigla' => 'GSC/SIS',
                'nivel' => '2',
                'dependencia'=> '31',
                'dependencia1'=> '0',
                'fkp_departamento'=>4,
            ],

            [
                'descripcion' => 'GERENCIA REGIONAL COCHABAMBA',
                'sigla' => 'GCB',
                'nivel' => '3',
                'dependencia'=> '0',
                'dependencia1'=> '0',
                'fkp_departamento'=>3,
            ],
            [
                'descripcion' => 'AREA TECNICA',
                'sigla' => 'GCB/RTE',
                'nivel' => '2',
                'dependencia'=> '36',
                'dependencia1'=> '0',
                'fkp_departamento'=>3,
            ],
            [
                'descripcion' => 'AREA ADMINISTRATIVA',
                'sigla' => 'GCB/RAD',
                'nivel' => '2',
                'dependencia'=> '36',
                'dependencia1'=> '0',
                'fkp_departamento'=>3,
            ],
            [
                'descripcion' => 'AREA JURIDICA',
                'sigla' => 'GCB/RJU',
                'nivel' => '2',
                'dependencia'=> '36',
                'dependencia1'=> '0',
                'fkp_departamento'=>3,
            ],
            [
                'descripcion' => 'AREA DE SISTEMAS',
                'sigla' => 'GCB/SIS',
                'nivel' => '2',
                'dependencia'=> '36',
                'dependencia1'=> '0',
                'fkp_departamento'=>3,
            ],

            [
                'descripcion' => 'GERENCIA REGIONAL BENI',
                'sigla' => 'GBN',
                'nivel' => '3',
                'dependencia'=> '0',
                'dependencia1'=> '0',
                'fkp_departamento'=>10,
            ],
            [
                'descripcion' => 'AREA TECNICA',
                'sigla' => 'GBN/RTE',
                'nivel' => '2',
                'dependencia'=> '41',
                'dependencia1'=> '0',
                'fkp_departamento'=>10,
            ],
            [
                'descripcion' => 'AREA ADMINISTRATIVA',
                'sigla' => 'GBN/RAD',
                'nivel' => '2',
                'dependencia'=> '41',
                'dependencia1'=> '0',
                'fkp_departamento'=>10,
            ],
            [
                'descripcion' => 'AREA JURIDICA',
                'sigla' => 'GBN/RJU',
                'nivel' => '2',
                'dependencia'=> '41',
                'dependencia1'=> '0',
                'fkp_departamento'=>10,
            ],
            [
                'descripcion' => 'AREA DE SISTEMAS',
                'sigla' => 'GBN/SIS',
                'nivel' => '2',
                'dependencia'=> '41',
                'dependencia1'=> '0',
                'fkp_departamento'=>10,
            ],

            [
                'descripcion' => 'GERENCIA REGIONAL PANDO',
                'sigla' => 'GPN',
                'nivel' => '3',
                'dependencia'=> '0',
                'dependencia1'=> '0',
                'fkp_departamento'=>9,
            ],
            [
                'descripcion' => 'AREA TECNICA',
                'sigla' => 'GPN/RTE',
                'nivel' => '2',
                'dependencia'=> '46',
                'dependencia1'=> '0',
                'fkp_departamento'=>9,
            ],
            [
                'descripcion' => 'AREA ADMINISTRATIVA',
                'sigla' => 'GPN/RAD',
                'nivel' => '2',
                'dependencia'=> '46',
                'dependencia1'=> '0',
                'fkp_departamento'=>9,
            ],
            [
                'descripcion' => 'AREA JURIDICA',
                'sigla' => 'GPN/RJU',
                'nivel' => '2',
                'dependencia'=> '46',
                'dependencia1'=> '0',
                'fkp_departamento'=>9,
            ],
            [
                'descripcion' => 'AREA DE SISTEMAS',
                'sigla' => 'GPN/SIS',
                'nivel' => '2',
                'dependencia'=> '46',
                'dependencia1'=> '0',
                'fkp_departamento'=>9,
            ],

            [
                'descripcion' => 'GERENCIA REGIONAL POTOSI',
                'sigla' => 'GPT',
                'nivel' => '2',
                'dependencia'=> '0',
                'dependencia1'=> '0',
                'fkp_departamento'=>5,
            ],
            [
                'descripcion' => 'AREA TECNICA',
                'sigla' => 'GPT/RTE',
                'nivel' => '2',
                'dependencia'=> '51',
                'dependencia1'=> '0',
                'fkp_departamento'=>5,
            ],
            [
                'descripcion' => 'AREA ADMINISTRATIVA',
                'sigla' => 'GPT/RAD',
                'nivel' => '2',
                'dependencia'=> '51',
                'dependencia1'=> '0',
                'fkp_departamento'=>5,
            ],
            [
                'descripcion' => 'AREA JURIDICA',
                'sigla' => 'GPT/RJU',
                'nivel' => '2',
                'dependencia'=> '51',
                'dependencia1'=> '0',
                'fkp_departamento'=>5,
            ],
            [
                'descripcion' => 'AREA DE SISTEMAS',
                'sigla' => 'GPT/SIS',
                'nivel' => '2',
                'dependencia'=> '51',
                'dependencia1'=> '0',
                'fkp_departamento'=>5,
            ],


            [
                'descripcion' => 'GERENCIA REGIONAL ORURO',
                'sigla' => 'GOR',
                'nivel' => '3',
                'dependencia'=> '0',
                'dependencia1'=> '0',
                'fkp_departamento'=>6,
            ],
            [
                'descripcion' => 'AREA TECNICA',
                'sigla' => 'GOR/RTE',
                'nivel' => '2',
                'dependencia'=> '56',
                'dependencia1'=> '0',
                'fkp_departamento'=>6,
            ],
            [
                'descripcion' => 'AREA ADMINISTRATIVA',
                'sigla' => 'GOR/RAD',
                'nivel' => '2',
                'dependencia'=> '56',
                'dependencia1'=> '0',
                'fkp_departamento'=>6,
            ],
            [
                'descripcion' => 'AREA JURIDICA',
                'sigla' => 'GOR/RJU',
                'nivel' => '2',
                'dependencia'=> '56',
                'dependencia1'=> '0',
                'fkp_departamento'=>6,
            ],
            [
                'descripcion' => 'AREA DE SISTEMAS',
                'sigla' => 'GOR/SIS',
                'nivel' => '2',
                'dependencia'=> '56',
                'dependencia1'=> '0',
                'fkp_departamento'=>6,
            ],

            [
                'descripcion' => 'GERENCIA REGIONAL TARIJA',
                'sigla' => 'GTJ',
                'nivel' => '3',
                'dependencia'=> '0',
                'dependencia1'=> '0',
                'fkp_departamento'=>8,
            ],
            [
                'descripcion' => 'AREA TECNICA',
                'sigla' => 'GTJ/RTE',
                'nivel' => '2',
                'dependencia'=> '61',
                'dependencia1'=> '0',
                'fkp_departamento'=>8,
            ],
            [
                'descripcion' => 'AREA ADMINISTRATIVA',
                'sigla' => 'GTJ/RAD',
                'nivel' => '2',
                'dependencia'=> '61',
                'dependencia1'=> '0',
                'fkp_departamento'=>8,
            ],
            [
                'descripcion' => 'AREA JURIDICA',
                'sigla' => 'GTJ/RJU',
                'nivel' => '2',
                'dependencia'=> '61',
                'dependencia1'=> '0',
                'fkp_departamento'=>8,
            ],
            [
                'descripcion' => 'AREA DE SISTEMAS',
                'sigla' => 'GTJ/SIS',
                'nivel' => '2',
                'dependencia'=> '61',
                'dependencia1'=> '0',
                'fkp_departamento'=>8,
            ],

            [
                'descripcion' => 'GERENCIA REGIONAL CHUQUISACA',
                'sigla' => 'GCH',
                'nivel' => '3',
                'dependencia'=> '0',
                'dependencia1'=> '0',
                'fkp_departamento'=>7,
            ],
            [
                'descripcion' => 'AREA TECNICA',
                'sigla' => 'GCH/RTE',
                'nivel' => '2',
                'dependencia'=> '66',
                'dependencia1'=> '0',
                'fkp_departamento'=>7,
            ],
            [
                'descripcion' => 'AREA ADMINISTRATIVA',
                'sigla' => 'GCH/RAD',
                'nivel' => '2',
                'dependencia'=> '66',
                'dependencia1'=> '0',
                'fkp_departamento'=>7,
            ],
            [
                'descripcion' => 'AREA JURIDICA',
                'sigla' => 'GCH/RJU',
                'nivel' => '2',
                'dependencia'=> '66',
                'dependencia1'=> '0',
                'fkp_departamento'=>7,
            ],
            [
                'descripcion' => 'AREA DE SISTEMAS',
                'sigla' => 'GCH/SIS',
                'nivel' => '2',
                'dependencia'=> '66',
                'dependencia1'=> '0',
                'fkp_departamento'=>7,
            ],

        ]);
    }
}
