<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProcesoVuelo extends Model
{
    use HasFactory;

    protected $table = 'proceso_vuelo';

    protected $fillable = [
        'id_amhs',
        'fecha',
        'hora',
        'vuelo',
        'tipo',
        'origen',
        'destino',
        'eobt',
        'puntos',
        'linea_aerea',
        'velocidad',
        'dep',
        'etd',
        'reg',
        'sel',
        'mensaje',
        'id_estado',
        'name_estado',
        'color_estado',
        'regla_tipo',
        'llave_select',
        'id_rutas_encontradas',
        'name_rutas_encontradas',
        'puntos_mensaje',
        'array_option_select',
        'id_vector_viaje',
        'name_vector_viaje',
        'distancia_vector_viaje',
        'ruta_vector_viaje',
        'selected',
        'atd',
        'est',
        'nivel',
        'sq',
        'ha',
        'est_array',
        'chg_ruta_array',
        'dt_cmp_array',
        'spl_punto_array',
        'spl_est',
        'activo',
        'fk_user',
        'fpl_id_punto',
        'fpl_punto',
        'fpl_id_ruta',
        'fpl_ruta',
        'fpl_punto_seleccionado',
        'fpl_distancia',
        'fpl_nivel',
        'primera_ficha',
        'tipo_fpl',
        'equipo',
        'eet',
        'opr',
        'turbulencia',
        'aeronaves',
        'aed_alternos',
        'dep_alt',
        'dest_alt',
        'ralt',
        'dof',
        'nav',
        'eet_alt',
        'rmk',
        'rif',
        'sts',
        'typ',
        'per',
        'com',
        'dat',
        'altn',
        'code',
        'rvr',
        'dta',
        'id_amhs_creado',
        'fecha_creado',
        'cerrado',
        'nivel_propuesto',
        'ruta_propuesta',
        'tipo_ficha',
        'nivel_tower',
        'eat_tower',
        'sub_tipo_ficha',
        'otros_datos',
        'dest2',
        'eta',
        'oaci',
        'traspaso',
        'tra',
        'fecha_impresion',
    ];
}
